name: Build and Test Spring Boot Application
on:
  push:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sourcecode
        uses: actions/checkout@v4
      - name: setup jdk 21
        uses:  actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Run Checkstyle (Printing Warnings)
        run: ./mvnw checkstyle:check -Dcheckstyle.failOnViolation=false
      - name: Run PMD (Printing Warnings)
        run: ./mvnw pmd:check -Dpmd.failOnViolation=false
  build:
    name: build spring boot appliaction
    runs-on: ubuntu-20.04
    steps:
      - name: checkout sourcecode
        uses: actions/checkout@v4

      - name: setup jdk 21
        uses:  actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: run integration tests
        run: mvn test

      - name: build application
        run: mvn clean install
